// client/src/app/shared/header/header.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { AuthService } from '../auth/auth.service';
import { Router } from '@angular/router';

@Component({
    selector: 'app-header',
    templateUrl: './header.component.html',
    styleUrls: [ './header.component.css' ]
})
export class HeaderComponent implements OnInit {
    @Output() loginChange = new EventEmitter();
    icon: string = '/assets/raspi.png';
    title: string = 'PiServer';
    authenticated: boolean = false;

    constructor(private authService: AuthService,
                private router: Router) {
    }

    ngOnInit() {
        this.authService.loginStatus
            .subscribe((authed) => {
                this.authenticated = authed;
            })
    }

    logout() {
        this.authService.logout();
        this.router.navigate(['/']);
        this.authenticated = false;
        // Emit logout
        this.loginChange.emit({
            authenticated: false
        });
    }

}

<header>
    <a [routerLink]="['']">
        <div class="title-container">
            <img class="icon" [src]="icon" alt="Raspberry pi">
            <h1 class="title">{{title}}</h1>
        </div>
    </a>
    <nav>
        <a class="btn-nav" [routerLink]="['/media']">Videos</a>
        <a class="btn-nav" [routerLink]="['/profile']">Profile</a>
        <a *ngIf="authenticated" class="btn-nav btn-logout" (click)="logout()">Logout</a>
    </nav>
    <img class="sidenav-toggle" src="/assets/icon-menu.svg" alt="burger menu">
</header>
<app-sidenav></app-sidenav>

// client/assets/header.jsx
import React from 'react';
import { Link } from 'react-router';

export default class HeaderComponent extends React.Component {

    constructor(props) {
        super(props);

        this.showSideNav = this.showSideNav.bind(this);
        this.hideSideNav = this.hideSideNav.bind(this);
    }

    showSideNav() {
        const sidenav = this.refs.sidenav;

        if (!sidenav) {
            return;
        }

        sidenav.className = 'sidenav sidenav-expanded';
    }

    hideSideNav() {
        const sidenav = this.refs.sidenav;

        if (!sidenav) {
            return;
        }

        sidenav.className = 'sidenav';
    }

    render() {
        return (<div>
                <header>
                    <Link to="/">
                        <div className="title-container">
                            <img className="icon" src="/img/raspi.png" alt="Raspberry pi"/>
                            <h1>{this.props.title}</h1>
                        </div>
                    </Link>
                    <nav>
                        <Link className="btn-nav" to="videos">Videos</Link>
                        <Link className="btn-nav" to="/user">Profile</Link>
                        <Link className="btn-nav btn-logout" to="/logout">Logout</Link>
                    </nav>
                    <img id="toggleSidenav" onClick={this.showSideNav} className="sidenav-toggle"
                         src="/img/icon-menu.svg" alt="Menu icon"/>
                </header>
                <div ref="sidenav" className="sidenav">
                    <div className="sidenav-header">
                        <h3 className="sidenav-title">Menu</h3>
                        <strong className="btn-sidenav-exit" onClick={this.hideSideNav}>x</strong>
                    </div>
                    <div className="sidenav-buttons">
                        <Link className="btn-sidenav" to="/">Home</Link>
                        <Link className="btn-sidenav" to="videos">Videos</Link>
                        <Link className="btn-sidenav" to="user">Profile</Link>
                        <Link className="btn-sidenav btn-sidenav-logout" to="logout">Logout</Link>
                    </div>
                </div>
            </div>
        );
    }
}
